### ISSUE TITLE
Remove window references from the dist/yawn.js package

### ISSUE THREAD

**Issue by jammi** [mohsen1/yawn-yaml#54]
I used your library with node, and at import, it throws an error.

My usage is like:
`import YAWN from 'yawn-yaml';`

..and I get an exception like:
```
.../node_modules/yawn-yaml/dist/yawn.js:97
var _yamlJs = (window.yaml);
              ^

ReferenceError: window is not defined
    at Object.3../error.js (.../node_modules/yawn-yaml/dist/yawn.js:97:15)
    at s (.../node_modules/yawn-yaml/dist/yawn.js:1:618)
    at e (.../node_modules/yawn-yaml/dist/yawn.js:1:789)
    at .../node_modules/yawn-yaml/dist/yawn.js:1:807
    at .../node_modules/yawn-yaml/dist/yawn.js:1:88
    at Object.<anonymous> (.../node_modules/yawn-yaml/dist/yawn.js:1:320)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
```

**Comment by mohsen1** [comment]
v2 should solve this
